---
title: Kyle Simpson's CV"
author: Kyle Simpson
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/custom_resume.css', 'css/styles.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---
  
```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)
library(tidyverse)
library(glue)
library(here)

PDF_EXPORT <- FALSE # Set this to true to have links turned into footnotes at the end of the document

links <- c() # Holds all the links that were inserted for placement at the end

source(here('R', 'parsing_functions.R')) # Functions for building sections from CSV data
source(here('R', 'common_variables.R'))  # Small variables for non-csv data such as intro text

position_data <- read_csv(here('data', 'positions.csv')) %>% # First let's get the data, filtering to only the items tagged as resume items
  filter(in_resume) 

```

Aside
================================================================================

{#contact} 
--------------------------------------------------------------------------------

```{r}
cat(sanitize_links(my_contacts))
```

Technical Skills {#skills}
--------------------------------------------------------------------------------
```{r}
build_skill_bars(skills)
```

Additional Skills {#add-skills}
--------------------------------------------------------------------------------
```{r other_skills}
other_skills
```

Education {#education_1}
--------------------------------------------------------------------------------

```{r edu_degree}
cat(sanitize_links(edu_degree))
```

```{r edu_location}
cat(sanitize_links(edu_location))
```

```{r edu_date}
cat(sanitize_links(edu_date))
```

```{r edu_city}
cat(sanitize_links(edu_city))
```

Certification {#certificate}
--------------------------------------------------------------------------------
```{r cert_degree}
cat(sanitize_links(cert_degree))
```

```{r cert_location}
cat(sanitize_links(cert_location))
```

```{r cert_date}
cat(sanitize_links(cert_date))
```

```{r cert_city}
cat(sanitize_links(cert_city))
```

Disclaimer {#disclaimer} 
-------------------------------------------------------------------------------- 
Page 1 of 1 


Main
================================================================================

Kyle PATRICK Simpson {#title}
--------------------------------------------------------------------------------
  
```{r my_title}
cat(sanitize_links(my_title)) 
```

```{r intro_text}
cat(sanitize_links(intro_text))
```

Relevant Work History {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('work_history')
```


\newpage <br>

Additional Work Experience {data-icon=briefcase}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('work_history_2')
```

Service & Internships {data-icon=bookmark}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('service')
```

Second page sidebar {.aside .extra-sidebar}
================================================================================

{#contact}
--------------------------------------------------------------------------------
```{r}
my_contacts
```

Licences & Certificates {#l_and_c}
--------------------------------------------------------------------------------
```{r}
licenses
```

Languages {#my_languages}
--------------------------------------------------------------------------------
```{r}
cat(sanitize_links(language_1))
```

```{r}
cat(sanitize_links(proficiency_1))
```

```{r}
cat(sanitize_links(language_2))
```

```{r}
cat(sanitize_links(proficiency_2))
```

```{r}
cat(sanitize_links(language_3))
```

```{r}
cat(sanitize_links(proficiency_3))
```

Hobbies & <br> Interests {#hobbies}
--------------------------------------------------------------------------------
```{r}
hobbies
```

References {#references}
--------------------------------------------------------------------------------
```{r}
my_references
```

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------
```{r}
my_disclaimer
```
